language: rust
rust:
  - nightly
os: linux
cache: cargo
# Remove the local crate's build files, as they only add bloat to the cache.
# TODO: Remove unused dependency build files
before_cache:
  - rm -rfv target/debug/{generate_handlers,lalafell_bot,liblalafell_bot}.d
  - rm -rfv target/debug/incremental/{generate_handlers,lalafell_bot,build_script_build}-*
  - rm -rfv target/debug/.fingerprint/lalafell_bot-*
  - rm -rfv target/debug/build/lalafell_bot-*
  - rm -rfv target/debug/deps/lalafell_bot-*
  - rm -rfv target/debug/deps/liblalafell_bot-*
  - cargo clean -p lalafell_bot
dist: trusty
before_script:
  - ./.travis_cache_check.sh
script:
  - cargo build --verbose --bin lalafell_bot
  - cargo build --verbose --features source --bin generate_handlers
notifications:
  email: false
