language: rust
rust:
  - nightly
os: linux
cache:
  directories:
    # Default directories for cargo cache
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
    # Our copy of libsodium
    - $HOME/libsodium
addons:
  apt:
    packages:
      - libopus-dev
# Remove the local crate's build files, as they only add bloat to the cache.
# TODO: Remove unused dependency build files
before_cache:
  - rm -rfv target/debug/{generate_handlers,lalafell_bot,liblalafell_bot}.d
  - rm -rfv target/debug/incremental/{generate_handlers,lalafell_bot,bot_command_derive,build_script_build}-*
  - rm -rfv target/debug/.fingerprint/{lalafell_bot,bot_command_derive}-*
  - rm -rfv target/debug/build/lalafell_bot-*
  - rm -rfv target/debug/deps/{lalafell_bot,liblalafell_bot,bot_command_derive,libbot_command_derive}-*
  - rm -rfv target/debug/deps/liblalafell_bot-*
  - cargo clean -p lalafell_bot
dist: trusty
before_script:
  - .travis/cache_check.sh
  - . .travis/libsodium.sh
script:
  - cargo build --verbose --bin lalafell_bot
  - cargo build --verbose --features source --bin generate_handlers
notifications:
  email: false
