language: rust
rust:
  - nightly
os:
  - linux
  - osx
cache: cargo
dist: trusty
script:
  - cargo build --bin lalafell_bot
  - cargo build --features source --bin generate_handlers
notifications:
  email: false
