language: rust
rust:
  - nightly
os:
  - linux
  # Disabled for now, since I don't want all my builds to take hours waiting for a macOS instance
  # - osx
cache: cargo
dist: trusty
script:
  - cargo build --bin lalafell_bot
  - cargo build --features source --bin generate_handlers
notifications:
  email: false
