[package]
name = "lalafell_bot"
version = "0.1.0"
authors = ["Kyle Clemens <me@kyleclemens.com>"]

[dependencies]
discord = "0.8"
xivdb = {version = "*", path = "../xivdb-rs"}
dotenv = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ctrlc = { version = "3.0", features = ["termination"] }
chrono = "0.3"
log = "0.3"
simplelog = "0.4"
