[package]
name = "lalafell_bot"
version = "0.1.0"
authors = ["Kyle Clemens <me@kyleclemens.com>"]

[dependencies]
lalafell = { version = "*", git = "https://github.com/jkcclemens/lalafell" }
xivdb = { version = "*", git = "https://github.com/jkcclemens/xivdb-rs" }
dotenv = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ctrlc = { version = "3.0", features = ["termination"] }
chrono = "0.4"
log = "0.4"
hyper = "0.11"
hyper-rustls = "0.11"
make_hyper_great_again = "0.11"
scraper = "0.4"
uuid = { version = "0.5", features = ["v4"] }
lazy_static = "1.0"
envy = "0.3"
error-chain = "0.11"
diesel = { version = "1.0", features = ["sqlite"] }
diesel_infer_schema = { version = "1.0", features = ["sqlite"] }
url = "1.6"
url_serde = "0.2"
byteorder = "1.2"
rand = "0.4"

[dependencies.serenity]
version = "0.5"
git = "https://github.com/zeyla/serenity"
branch = "v0.5.0"
default-features = false
features = ["builder", "cache", "client", "gateway", "model", "utils"]
