[package]
name = "lalafell_bot"
version = "0.1.0"
authors = ["Kyle Clemens <me@kyleclemens.com>"]

[dependencies]
discord = { version = "*", path = "./discord-rs" }
xivdb = { version = "*", path = "./xivdb-rs" }
dotenv = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ctrlc = { version = "3.0", features = ["termination"] }
chrono = "0.3"
log = "0.3"
fern = "0.4"
ansi_term = "0.9"
hyper = "0.10"
scraper = "0.4"
uuid = { version = "0.5", features = ["v4"] }
