[package]
name = "lalafell_bot"
version = "0.1.0"
authors = ["Kyle Clemens <me@kyleclemens.com>"]

[dependencies]
discord = { version = "*", git = "https://github.com/jkcclemens/discord-rs" }
xivdb = { version = "*", git = "https://github.com/jkcclemens/xivdb-rs" }
dotenv = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ctrlc = { version = "3.0", features = ["termination"] }
chrono = "0.3"
log = "0.3"
fern = "0.4"
ansi_term = "0.9"
hyper = "0.11"
hyper-rustls = "0.7"
make_hyper_great_again = { version = "0.11", git = "https://github.com/jkcclemens/make_hyper_great_again" }
scraper = "0.4"
uuid = { version = "0.5", features = ["v4"] }
lazy_static = "0.2"
envy = "0.3"
selectors = "0.18"
error-chain = "0.10"
