unstable_features = true

indent_style = "block"

max_width = 120

wrap_comments = true
comment_width = 120
normalize_comments = true

format_strings = true

hard_tabs = false
tab_spaces = 2

merge_imports = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true

match_block_trailing_comma = true

use_field_init_shorthand = true
use_try_shorthand = true
